name: hvpvault-packer-hcppacker
# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "development"
      - "staging"
      - "main"

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  #HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  #HCP_BUCKET_NAME: "learn-packer-github-actions"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      iteration_id: ${{ steps.hcp.outputs.iteration_id }}
    steps:
    - uses: actions/checkout@v2
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.4.0
      with:
          url: https://dp-vault-cluster.vault.1e53275e-94b7-4575-b679-735c6df54970.aws.hashicorp.cloud:8200
          tlsSkipVerify: true
          namespace: admin
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            azure/creds/edu-app client_id | AZURE_CLIENT_ID;
            azure/creds/edu-app client_secret | AZURE_SECRET_ID;

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Az Credentials
      uses: azure/actions/login@v1
      with:
        #client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      env:
        AZURE_SECRET_ID: ${{ steps.secrets.outputs.AZURE_SECRET_ID }}
        AZURE_CLIENT_ID: ${{ steps.secrets.AZURE_CLIENT_ID }}  

    - name: Packer Init
      run: packer init ../hcp-packer-ubuntu20

    - name: Packer Build - Branches
      if: "startsWith(github.ref, 'refs/heads/')"
      run: packer build ../hcp-packer-ubuntu20

    - name: Packer Build - Tags
      if: startsWith(github.ref, 'refs/tags/v')
      run: HCP_PACKER_BUILD_FINGERPRINT=$(date +'%m%d%YT%H%M%S') packer build .

